# Generated by Django 4.2.7 on 2024-04-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='контр-агент')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки письма')),
                ('date_of_inspection', models.DateField(blank=True, null=True, verbose_name='Дата проверки')),
                ('counterparty_form', models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Физическое лицо', 'Физическое лицо')], default='Юридическое лицо', max_length=50, verbose_name='Форма КА')),
                ('report_status', models.CharField(choices=[('verified', 'Проверен'), ('not_verified', 'Не проверен'), ('under_inspection', 'На проверке')], default='not_verified', max_length=50, verbose_name='Статус проверки')),
                ('is_active', models.BooleanField(choices=[(True, 'Действующий'), (False, 'Не действующий')], default=True, verbose_name='Статус')),
                ('file_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filereport', verbose_name='Отчет отправки письма')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-date_of_inspection'],
            },
        ),
    ]
