# Generated by Django 4.2.7 on 2024-05-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-date_of_inspection'], 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='filereport',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='file_report',
        ),
    ]
