# Generated by Django 4.2.7 on 2024-05-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_agent_options_alter_filereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereport',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.agent', verbose_name='Агент'),
        ),
    ]
