# Generated by Django 4.2.7 on 2024-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agent_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='inn',
            field=models.CharField(max_length=15, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='report_status',
            field=models.CharField(choices=[('Проверен', 'Проверен'), ('Не проверен', 'Не проверен'), ('На проверке', 'На проверке')], default='Не проверен', max_length=50, verbose_name='Статус проверки'),
        ),
    ]
